### PR TITLE
Add note about cursor plugins

### PR DESCRIPTION
**Pull request by dminkovsky**
I spent a little while confused why I followed the image upload example but didn't get the same cursor behavior. I tracked it down. Maybe something like this would help other people?

### CODE REVIEW

**Comment by dminkovsky** [comment]
Thanks a lot for the review @kamagatos. I made those corrections.

Generally, do you think this is a good addition?

**Comment by marijnh** [comment]
This seems very specific. Almost all the demos use those plugins. And other plugins too, since they use `basic-setup`. Why do we need a specific note about these?

**Comment by dminkovsky** [comment]
Yeah that's what I was thinking: this note is not specific to this test. Maybe somehow explain how to see the complete code listing? Because that took me a bit of time and confusion, as explained above.

**Comment by marijnh** [comment]
Sorry, I don't feel that these add a lot. The fact that editor's can be configured differently should be clear by the time one is working through these examples, and the glitch link already serves as a link to the source code.

**Comment by dminkovsky** [comment]
Ah I don't use glitch, didn't know that's what it was. Makes sense thanks.

**Comment by dminkovsky** [comment]
Yeah looking at it again and "Remix on Glitch"--I wish that was something like "View on Codesandbox" or something... why do they have to use that terminology. I didn't even know Glitch was one of these web apps. Or maybe I did and forgot.

**Pull request closed without merging**
